# SERVER

quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}


# DATASOURCE - MYSQL

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/feedback?useSSL=false&allowPublicKeyRetrieval=true}
quarkus.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
quarkus.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# === TEST ===
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=

%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create


# HIBERNATE ORM

# update apenas para DEV / DEMO
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true


# RABBITMQ - PRODUCER (ENVIA EVENTOS)

mp.messaging.outgoing.feedback-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.feedback-out.exchange.name=feedback-exchange
mp.messaging.outgoing.feedback-out.exchange.type=topic
mp.messaging.outgoing.feedback-out.routing-key=feedback.avaliacao
mp.messaging.outgoing.feedback-out.durable=true


# RABBITMQ - CONSUMER (RECEBE EVENTOS)

mp.messaging.incoming.feedback-in.connector=smallrye-rabbitmq
mp.messaging.incoming.feedback-in.exchange.name=feedback-exchange
mp.messaging.incoming.feedback-in.exchange.type=topic
mp.messaging.incoming.feedback-in.queue.name=feedback-queue
mp.messaging.incoming.feedback-in.routing-key=feedback.avaliacao
mp.messaging.incoming.feedback-in.durable=true
mp.messaging.incoming.feedback-in.auto-acknowledgement=true


# JWT / SECURITY

mp.jwt.verify.issuer=fiap-api
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem


# SEGURANÇA GLOBAL

# Tudo protegido por padrão
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Login liberado sem autenticação
quarkus.http.auth.permission.public.paths=/auth/*
quarkus.http.auth.permission.public.policy=permit
